version: '3.9'

services:
  web:
    build: .
    image: twitter-clone-image
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
  migration:
    image: twitter-clone-image
    command: python manage.py migrate
