# Generated by Django 4.2.16 on 2025-01-11 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0004_tweets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name_plural': 'Tweets'},
        ),
        migrations.AddField(
            model_name='tweets',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
